# This file configures the bookshelf application frontend. The frontend serves
# public web traffic.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logging-frontend
  labels:
    app: logging
    tier: frontend
# The logging frontend replica set ensures that at least 3
# instances of the logging app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: logging
        tier: frontend
    spec:
      containers:
      - name: logging-app
        # TODO: Replace [YOUR_PROJECT_ID] with your project ID.
        image: gcr.io/demogeauxcommerce/logging:latest
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        # The bookshelf process listens on port 8080 for web traffic by default.
        ports:
        - name: http-server
          containerPort: 8080
